# Generated by Django 5.1.3 on 2024-11-09 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="article",
            old_name="content",
            new_name="summary",
        ),
        migrations.RemoveField(
            model_name="article",
            name="author",
        ),
        migrations.AddField(
            model_name="article",
            name="author_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="article",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
