# Generated by Django 5.1.3 on 2024-11-09 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_rename_content_article_summary_remove_article_author_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="path",
            field=models.CharField(
                blank=True,
                help_text="Direct URL path to the article's dedicated page",
                max_length=255,
            ),
        ),
    ]
