# Generated by Django 5.1.3 on 2024-11-22 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_article_group_article_image_path"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="order",
            field=models.IntegerField(
                default=0, help_text="Order of the article for sorting purposes"
            ),
        ),
    ]
